@startuml UC16_ReportBug
autonumber

actor "Passenger" as Passenger
participant "System" as Sys
database "Airport Database" as DB
actor "System Administrator" as SystemAdministrator

Passenger -> Sys : Click "Report a bug"
Sys -> Passenger : Request bug information
Passenger -> Sys : Submit bug details
Sys -> DB : Create bug ticket
DB --> Sys : Ticket saved
Sys -> SystemAdministrator : Notify bug report
Sys -> Passenger : Display success message

@enduml